### ISSUE TITLE
lol /home/paultag/keyring

### ISSUE THREAD

**Issue by tianon** [paultag/inept#2]
Given that you have a `--keyring` flag, I think this is a bug: https://github.com/paultag/inept/blob/2a1fe58c24c203b204025915a87e59c259fc969f/cmd/inept/main.go#L52

``` go
func getOpenPGPKey(keyid uint64) (*openpgp.Entity, error) {
    fd, err := os.Open("/home/paultag/keyring")
    // ...
```

Perhaps `getOpenPGPKey` needs to also take the path the keyring?

**Comment by paultag** [comment]
totally a bug
